// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JupiterSwaps {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<JupiterTrade>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JupiterTrade {
    #[prost(string, tag="1")]
    pub dapp: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub block_time: i64,
    #[prost(uint64, tag="3")]
    pub block_slot: u64,
    #[prost(string, tag="4")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub signer: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub source_token_account: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub destination_token_account: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub source_mint: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub destination_mint: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub in_amount: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub quoted_out_amount: ::prost::alloc::string::String,
    #[prost(uint32, tag="12")]
    pub in_decimals: u32,
    #[prost(uint32, tag="13")]
    pub quoted_decimals: u32,
    #[prost(string, tag="14")]
    pub instruction_type: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
